# Form implementation generated from reading ui file 'hoadon.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 555)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #ffa9f9, /* Hồng nhạt bên trái */\n"
"        stop:1 #d98bbf); /* Hồng đậm bên phải */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 468, 77, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_Film_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Film_4.setGeometry(QtCore.QRect(128, 476, 309, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_Film_4.setFont(font)
        self.label_Film_4.setStyleSheet("")
        self.label_Film_4.setText("")
        self.label_Film_4.setObjectName("label_Film_4")
        self.label_giaodien = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_giaodien.setGeometry(QtCore.QRect(0, -4, 445, 529))
        self.label_giaodien.setText("")
        self.label_giaodien.setPixmap(QtGui.QPixmap("../../OneDrive/Hình ảnh/Ung dung quan ly & ban ve xem phim (1080 x 1920 px) (1080 x 1920 px) (1920 x 1920 px) (1920 x 2100 px) (1920 x 2200 px) (1920 x 2300 px) (1).png"))
        self.label_giaodien.setScaledContents(True)
        self.label_giaodien.setObjectName("label_giaodien")
        self.label_Suatchiu = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Suatchiu.setGeometry(QtCore.QRect(152, 164, 261, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_Suatchiu.setFont(font)
        self.label_Suatchiu.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_Suatchiu.setText("")
        self.label_Suatchiu.setObjectName("label_Suatchiu")
        self.label_Film = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Film.setGeometry(QtCore.QRect(108, 124, 333, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_Film.setFont(font)
        self.label_Film.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_Film.setText("")
        self.label_Film.setObjectName("label_Film")
        self.label_chair = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_chair.setGeometry(QtCore.QRect(100, 200, 261, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_chair.setFont(font)
        self.label_chair.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_chair.setText("")
        self.label_chair.setObjectName("label_chair")
        self.label_veticket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_veticket.setGeometry(QtCore.QRect(216, 272, 29, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_veticket.setFont(font)
        self.label_veticket.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_veticket.setText("")
        self.label_veticket.setObjectName("label_veticket")
        self.label_cornbig = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cornbig.setGeometry(QtCore.QRect(216, 308, 29, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_cornbig.setFont(font)
        self.label_cornbig.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_cornbig.setText("")
        self.label_cornbig.setObjectName("label_cornbig")
        self.label_cornmini = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cornmini.setGeometry(QtCore.QRect(216, 348, 29, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_cornmini.setFont(font)
        self.label_cornmini.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_cornmini.setText("")
        self.label_cornmini.setObjectName("label_cornmini")
        self.label_pepsi = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pepsi.setGeometry(QtCore.QRect(216, 388, 29, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_pepsi.setFont(font)
        self.label_pepsi.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_pepsi.setText("")
        self.label_pepsi.setObjectName("label_pepsi")
        self.label_tongall = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tongall.setGeometry(QtCore.QRect(216, 428, 149, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_tongall.setFont(font)
        self.label_tongall.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_tongall.setText("")
        self.label_tongall.setObjectName("label_tongall")
        self.label_tongticket = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tongticket.setGeometry(QtCore.QRect(308, 272, 149, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_tongticket.setFont(font)
        self.label_tongticket.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_tongticket.setText("")
        self.label_tongticket.setObjectName("label_tongticket")
        self.label_tongcornbig = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tongcornbig.setGeometry(QtCore.QRect(308, 308, 149, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_tongcornbig.setFont(font)
        self.label_tongcornbig.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_tongcornbig.setText("")
        self.label_tongcornbig.setObjectName("label_tongcornbig")
        self.label_tongcornmini = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tongcornmini.setGeometry(QtCore.QRect(308, 348, 149, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_tongcornmini.setFont(font)
        self.label_tongcornmini.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_tongcornmini.setText("")
        self.label_tongcornmini.setObjectName("label_tongcornmini")
        self.label_tongpepsi = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_tongpepsi.setGeometry(QtCore.QRect(308, 388, 137, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_tongpepsi.setFont(font)
        self.label_tongpepsi.setStyleSheet("QLabel {\n"
"z-index: 999;\n"
"}")
        self.label_tongpepsi.setText("")
        self.label_tongpepsi.setObjectName("label_tongpepsi")
        self.pushButton_QR = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_QR.setGeometry(QtCore.QRect(8, 484, 209, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_QR.setFont(font)
        self.pushButton_QR.setStyleSheet("QPushButton {\n"
"    background-color: #ff69b4; /* Màu hồng */\n"
"    border: 2px solid rgb(255, 212, 243); \n"
"    border-radius: 20px; \n"
"    font: bold 9pt;\n"
"    color: white;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 185, 255); /* Màu vàng khi hover */\n"
"    color: black;\n"
"    border: 3px dashed #ff69b4; /* Viền đứt đẹp đẹp */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 203, 224); \n"
"    color: white;\n"
"    border: 3px solid rgb(255, 169, 230);\n"
"}\n"
"")
        self.pushButton_QR.setObjectName("pushButton_QR")
        self.pushButton_tienmat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_tienmat.setGeometry(QtCore.QRect(224, 484, 209, 41))
        self.pushButton_tienmat.setStyleSheet("QPushButton {\n"
"    background-color: #ff69b4; /* Màu hồng */\n"
"    border: 2px solid rgb(255, 212, 243); \n"
"    border-radius: 20px; \n"
"    font: bold 9pt;\n"
"    color: white;\n"
"    padding: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(253, 185, 255); /* Màu vàng khi hover */\n"
"    color: black;\n"
"    border: 3px dashed #ff69b4; /* Viền đứt đẹp đẹp */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 203, 224); \n"
"    color: white;\n"
"    border: 3px solid rgb(255, 169, 230);\n"
"}\n"
"")
        self.pushButton_tienmat.setObjectName("pushButton_tienmat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Phim:"))
        self.pushButton_QR.setText(_translate("MainWindow", "Thanh toán bằng QR"))
        self.pushButton_tienmat.setText(_translate("MainWindow", "Thanh toán bằng tiền mặt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
